{
 "title": "Consumer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "POD Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Limits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request & Limits - memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "POD Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=\"$namespace\",pod=\"$pod\"}) by (namespace, pod, phase)) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD Restart",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}